# Generated by Django 3.2 on 2025-03-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_kg',
        ),
        migrations.AddField(
            model_name='farmer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_images/'),
        ),
    ]
