# Generated by Django 3.2 on 2025-03-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tea_type',
            field=models.CharField(default='Black Tea', max_length=50),
            preserve_default=False,
        ),
    ]
