# Generated by Django 3.2 on 2025-03-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_tea_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tea_type',
            field=models.CharField(default='Black Tea', max_length=255),
        ),
    ]
